export const GET_ITEMS = 'GET_ITEMS'
export const UPDATE_ITEMS = 'UPDATE_ITEMS'
export const DELETE_ITEMS = 'DELETE_ITEMS'
export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'
export const SET_USER = 'SET_USER'
